spring:
  datasource:
    url: jdbc:mysql://myserver:8505/db02?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
# 配置 Redis
  redis:
    host: myserver
    port: 8540
# 开启驼峰命名法
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# SQL 语句日志
logging:
  level:
    com:
      jiang:
        mapper: debug

